config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/gitmate/open-source/IGitt:
      branch: master
      repo: https://gitlab.com/gitmate/open-source/IGitt
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/gitmate/open-source/IGitt git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-tomato-grasshopper.sh
        container: qc.acc_muggy-olive-coyote
  QC.Doc:
    repos:
      gitlab.com/gitmate/open-source/IGitt find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-silver-paradise.sh
        container: qc.doc_freaky-cerise-robin
      gitlab.com/gitmate/open-source/IGitt git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ochre-worm.sh
        container: qc.doc_hilly-persimmon-dragon
      gitlab.com/gitmate/open-source/IGitt restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-teal-badger.sh
        container: qc.doc_skimpy-mauve-spoonbill
  QC.FAIR:
    repos:
      gitlab.com/gitmate/open-source/IGitt F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-heliotrope-shrew.sh
        container: qc.fair_pokey-pumpkin-squid
  QC.Lic:
    repos:
      gitlab.com/gitmate/open-source/IGitt licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-vermilion-shrimp.sh
        container: qc.lic_droopy-bistre-barnacle
  QC.Sec:
    repos:
      gitlab.com/gitmate/open-source/IGitt bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-eggplant-caterpillar.sh
        container: qc.sec_cozy-ruby-cattle
  QC.Sty:
    repos:
      gitlab.com/gitmate/open-source/IGitt flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cinnabar-fowl.sh
        container: qc.sty_zippy-platinum-indri
  QC.Ver:
    repos:
      gitlab.com/gitmate/open-source/IGitt get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-pink-swan.sh
        container: qc.ver_woozy-orchid-cockroach
timeout: 1800
